name: plate_recognition
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  image_picker: ^0.8.5+3
  camera: ^0.10.0+1
  path_provider: ^2.0.11

  #firebase
  firebase_core: ^1.22.0
  cloud_firestore: ^3.4.7

  #websocket
  web_socket_channel: ^2.2.0

  #Mlkit plugins
  google_mlkit_commons: ^0.2.0
  google_mlkit_text_recognition: ^0.4.0
  google_mlkit_object_detection: ^0.5.0

  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ml/object_labeler.tflite
    - assets/plate.png
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg
